version: "2"

services:
  db:
    build: ./database
    image: mytoolbox/postgres

  wiki:
    build: ./back/wiki/target/docker/stage
    image: mytoolbox/wiki

  ipbase:
    build: ./back/ipbase/target/docker/stage
    image: mytoolbox/ipbase

  ui:
    build: ./front
    image: mytoolbox/ui

  hap-base:
    build: ./loadbalancer/haproxy
    image: training/haproxy